import React, { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Mail, MessageCircle, Linkedin, RotateCcw, Wand2, Save, Star, Globe2, Search } from 'lucide-react'
import PageHeader from '../components/ui/PageHeader.jsx'
import Badge, { scoreVariant } from '../components/ui/Badge.jsx'
import {
  businesses, generateEmailDraft, generateWhatsAppDraft, generateLinkedInDraft,
} from '../data/mockData.js'
import { useToast } from '../components/ui/Toast.jsx'

const tabs = [
  { key: 'email', label: 'Email', icon: Mail },
  { key: 'whatsapp', label: 'WhatsApp', icon: MessageCircle },
  { key: 'linkedin', label: 'LinkedIn', icon: Linkedin },
]

function draftFor(tab, biz) {
  if (tab === 'email') return generateEmailDraft(biz)
  if (tab === 'whatsapp') return generateWhatsAppDraft(biz)
  return generateLinkedInDraft(biz)
}

export default function Outreach() {
  const [params, setParams] = useSearchParams()
  const showToast = useToast()
  const preselected = params.get('biz')

  const [selectedId, setSelectedId] = useState(preselected || businesses.find((b) => b.website)?.id)
  const [tab, setTab] = useState('email')
  const [draft, setDraft] = useState(null)
  const [query, setQuery] = useState('')

  const biz = businesses.find((b) => b.id === selectedId) || businesses[0]

  useEffect(() => {
    setDraft(draftFor(tab, biz))
  }, [tab, biz.id])

  function regenerate(mode) {
    const base = draftFor(tab, biz)
    let body = base.body
    if (mode === 'shorter') {
      body = body.split('\n').filter(Boolean).slice(0, 3).join('\n\n')
    } else if (mode === 'professional') {
      body = body.replace(/!/g, '.').replace(/👋/g, '')
    } else if (mode === 'personalized') {
      body = `Hi ${biz.owner.split(' ')[0]}, quick note specifically about ${biz.name} in ${biz.location.split(',')[0]} —\n\n` + body
    }
    setDraft({ ...base, body })
    showToast('Draft regenerated by AI agent.')
  }

  const results = query.length > 1
    ? businesses.filter((b) => b.name.toLowerCase().includes(query.toLowerCase())).slice(0, 6)
    : []

  return (
    <div className="space-y-6">
      <PageHeader title="Outreach" subtitle="Review and refine AI-generated outreach before your team sends it." />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* Lead info */}
        <div className="bg-bg-card border border-border rounded-xl p-5 space-y-4">
          <div className="relative">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-muted" />
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Switch lead..."
              className="w-full bg-bg border border-border rounded-lg py-2 pl-8 pr-3 text-xs text-ink placeholder:text-ink-muted focus-ring outline-none focus:border-brand/50"
            />
            {results.length > 0 && (
              <div className="absolute top-full mt-1.5 w-full bg-bg border border-border rounded-lg shadow-card overflow-hidden z-10">
                {results.map((b) => (
                  <button
                    key={b.id}
                    onClick={() => { setSelectedId(b.id); setQuery(''); setParams({ biz: b.id }) }}
                    className="w-full text-left px-3 py-2 text-xs text-ink hover:bg-white/5"
                  >
                    {b.name}
                  </button>
                ))}
              </div>
            )}
          </div>

          <div>
            <h2 className="text-base font-semibold text-ink">{biz.name}</h2>
            <p className="text-xs text-ink-muted mt-0.5">{biz.industry} · {biz.location}</p>
          </div>

          <div className="flex items-center gap-2">
            <Badge variant={scoreVariant(biz.opportunityScore)}>{biz.opportunityScore} Opportunity</Badge>
          </div>

          <dl className="space-y-2.5 text-xs pt-2 border-t border-border">
            <div className="flex justify-between"><dt className="text-ink-muted">Owner</dt><dd className="text-ink">{biz.owner}</dd></div>
            <div className="flex justify-between items-center"><dt className="text-ink-muted flex items-center gap-1"><Globe2 size={12} />Website</dt><dd className="text-ink">{biz.website || 'None'}</dd></div>
            <div className="flex justify-between items-center"><dt className="text-ink-muted flex items-center gap-1"><Star size={12} />Reviews</dt><dd className="text-ink">{biz.reviews}</dd></div>
          </dl>
        </div>

        {/* Message editor */}
        <div className="lg:col-span-2 bg-bg-card border border-border rounded-xl p-5">
          <div className="flex items-center gap-1 bg-bg border border-border rounded-lg p-1 w-fit mb-4">
            {tabs.map((t) => (
              <button
                key={t.key}
                onClick={() => setTab(t.key)}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
                  tab === t.key ? 'bg-brand/15 text-brand-accent' : 'text-ink-muted hover:text-ink'
                }`}
              >
                <t.icon size={13} /> {t.label}
              </button>
            ))}
          </div>

          {draft && (
            <div className="space-y-3">
              {tab === 'email' && (
                <input
                  value={draft.subject}
                  onChange={(e) => setDraft({ ...draft, subject: e.target.value })}
                  className="w-full bg-bg border border-border rounded-lg py-2.5 px-3 text-sm text-ink font-medium focus-ring outline-none focus:border-brand/50"
                />
              )}
              <textarea
                value={draft.body}
                onChange={(e) => setDraft({ ...draft, body: e.target.value })}
                rows={12}
                className="w-full bg-bg border border-border rounded-lg py-3 px-3.5 text-sm text-ink leading-relaxed focus-ring outline-none focus:border-brand/50 resize-none"
              />
            </div>
          )}

          <div className="flex flex-wrap items-center gap-2 mt-4">
            <button onClick={() => regenerate('base')} className="inline-flex items-center gap-1.5 border border-border text-ink-muted hover:text-ink text-xs px-3 py-1.5 rounded-lg transition-colors">
              <RotateCcw size={12} /> Regenerate
            </button>
            <button onClick={() => regenerate('shorter')} className="inline-flex items-center gap-1.5 border border-border text-ink-muted hover:text-ink text-xs px-3 py-1.5 rounded-lg transition-colors">
              <Wand2 size={12} /> Make Shorter
            </button>
            <button onClick={() => regenerate('professional')} className="inline-flex items-center gap-1.5 border border-border text-ink-muted hover:text-ink text-xs px-3 py-1.5 rounded-lg transition-colors">
              <Wand2 size={12} /> Make Professional
            </button>
            <button onClick={() => regenerate('personalized')} className="inline-flex items-center gap-1.5 border border-border text-ink-muted hover:text-ink text-xs px-3 py-1.5 rounded-lg transition-colors">
              <Wand2 size={12} /> Make More Personalized
            </button>
            <button
              onClick={() => showToast('Draft saved.')}
              className="ml-auto inline-flex items-center gap-1.5 bg-brand hover:bg-brand/90 text-white text-xs font-medium px-4 py-2 rounded-lg transition-colors shadow-glow"
            >
              <Save size={13} /> Save Draft
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
